# Default override file for local development
version: "3.3"
services:
  app:
    build: .
    volumes:
      - '.:/app'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.awair-prometheus-exporter.rule=Host(`awair-prometheus-exporter.sat.joost.cx`)"
      - "traefik.http.routers.awair-prometheus-exporter.entrypoints=web"
    networks:
      - traefik
networks:
  traefik:
    external: true
